stages:
  - test

test-full-stack:
  stage: test
  image: docker:24.0 # Используем образ с Docker
  services:
    - name: docker:24.0-dind # Запускаем Docker-in-Docker (dind)
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: "" # Упрощаем подключение, отключая TLS для dind
  before_script:
    - apk add --no-cache docker-compose # Устанавливаем docker-compose
  script:
    # 1. Поднимаем ВЕСЬ стек (app, db, worker, broker) в фоновом режиме
    - docker-compose -f docker-compose.yml up -d

    # 2. Ждем, пока все сервисы (особенно БД и брокер) станут здоровыми
    - echo "Ждем, пока стек поднимется..."
    - sleep 30
    # Лучше использовать скрипт для проверки здоровья, но sleep для простоты

    # 3. Запускаем тесты ВНУТРИ контейнера с приложением
    # Ключ -T отключает псевдо-TTY, что необходимо для CI
    - docker-compose exec -T app alembic upgrade head
    - docker-compose exec -T app python -m pytest /app/tests/

    # 4. Останавливаем и очищаем стек
  after_script:
    - docker-compose down
  