image: docker

services:
  - docker:dind

before_script:
  - docker compose build

stages:
  - test
  - deploy

tests-job:
  stage: test
  script:
    - echo "✅ Running tests..."
    - docker compose up -d
    - docker compose exec service_a poetry run pytest
    - docker compose exec service_b poetry run pytest
  after_script:
    - docker compose down

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "🚀 Deploying application (on CI runner)..."
    - docker compose up -d
