stages:
  - test

run_service_a_tests:
  stage: test
  image: docker/compose:latest
  services:
    - name: docker:28.4.0-rc.2-dind
      alias: docker
  variables:
    POSTGRES_HOST: database_a
    RABBITMQ_HOST: rabbitmq
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker-compose --version
  script:
    - docker-compose up -d
    - until docker-compose exec -T database_a pg_isready -U $SERVICE_A_DB_USER; do sleep 2; done
    - docker-compose exec -T service_a poetry run alembic upgrade head
    - docker-compose exec -T service_a poetry run pytest
    - docker-compose down -v
  