stages:
  - test

run_service_a_tests:
  stage: test
  image: docker/compose:latest
  services:
    - name: docker:28.4.0-rc.2-dind
      alias: docker
  variables:
    SERVICE_A_TEST_DB_NAME: $SERVICE_A_TEST_DB_NAME
    DB_USER: $SERVICE_A_DB_USER
    DB_PASSWORD: $SERVICE_A_DB_PASSWORD
    DB_HOST: $SERVICE_A_DB_HOST
    DB_PORT: $SERVICE_A_DB_PORT
    RABBIT_USER: $RABBIT_USER
    RABBIT_PASS: $RABBIT_PASS
    CHECK_OUTBOX_EVENTS_EVERY: $CHECK_OUTBOX_EVENTS_EVERY
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker-compose --version
  script:
    - docker-compose up -d
    - until docker-compose exec -T database_a pg_isready -U $SERVICE_A_DB_USER; do sleep 2; done
    - docker-compose exec -T service_a poetry run alembic upgrade head
    - docker-compose exec -T service_a poetry run pytest
    - docker-compose down -v
  