"""Initial migration

Revision ID: 0617f0ae1ca0
Revises:
Create Date: 2025-08-20 17:59:06.312367

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0617f0ae1ca0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "received_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("recieved_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("received_item")
    # ### end Alembic commands ###
